name: Build edk2-rk3399

on:
  push:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt remove git
        sudo apt autoremove
        sudo apt install -y git build-essential uuid-dev iasl git nasm python3-distutils gcc-7-aarch64-linux-gnu

    - name: Clone repositories
      run: |
        mkdir workspace-edk2
        cd workspace-edk2
        git config --global protocol.file.allow always
        git clone https://github.com/tianocore/edk2.git -b edk2-stable202005 --recursive --depth=1
        $(cd edk2 && git checkout 2a7a122)
        pwd && ls 
        git clone https://github.com/tianocore/edk2-platforms.git -o cfdc7f907d545b14302295b819ea078bc36c6a40 --recursive --depth=1
        git clone https://github.com/strongtz/edk2-rk3399

    - name: Build edk2-rk3399
      working-directory: workspace-edk2/edk2-rk3399
      run: |
        bash build.sh --device polaris
